# Operación Forum

Se trata de un CCS CLFCLP Fija vs Fija a 3Y donde el Banco recibe CLP y paga CLF.

## Librerías

In [18]:
import qcfinancial as qcf
import aux_functions as aux

## Características Comunes de Ambas Patas

In [3]:
str_maturity = "3Y"
maturity = qcf.Tenor(str_maturity)
meses = maturity.get_months() + 12 * maturity.get_years()

In [15]:
common_parameters = {
    "settlement_periodicity": qcf.Tenor('6M'),
    "start_date": (start_date:=qcf.QCDate(13, 10, 2025)),
    "end_date": start_date.add_months(meses),
    "bus_adj_rule": qcf.BusyAdjRules.MODFOLLOW,
    "settlement_calendar": qcf.BusinessCalendar(start_date, 5),
    "settlement_stub_period": qcf.StubPeriod.NO,
    "settlement_lag": 0,
    "amort_is_cashflow": True,
    "sett_lag_behaviour": qcf.SettLagBehaviour.DONT_MOVE,
    "is_bond":False,
}

## Pata Fija en CLF (Banco recibe)

In [32]:
fixed_rate_value = .0356
clf_leg_other_values = {
    "rec_pay": qcf.RecPay.PAY,
    "initial_notional": 1_000_000.0,
    "notional_currency": qcf.QCCLF(),
    "interest_rate": qcf.QCInterestRate(fixed_rate_value, qcf.QCAct360(), qcf.QCLinearWf()),
}

In [33]:
pata_clf = qcf.LegFactory.build_bullet_fixed_rate_leg(
     **(common_parameters | clf_leg_other_values)
)

In [34]:
aux.leg_as_dataframe(pata_clf)

,fecha_inicial,fecha_final,fecha_pago,nocional,amortizacion,interes,amort_es_flujo,flujo,moneda_nocional,valor_tasa,tipo_tasa
0,2025-10-13,2026-04-13,2026-04-13,-1000000.0,0.0,-17997.777778,True,-1.799778e+04,CLF,0.0356,LinAct360
1,2026-04-13,2026-10-13,2026-10-13,-1000000.0,0.0,-18096.666667,True,-1.809667e+04,CLF,0.0356,LinAct360
2,2026-10-13,2027-04-13,2027-04-13,-1000000.0,0.0,-17997.777778,True,-1.799778e+04,CLF,0.0356,LinAct360
3,2027-04-13,2027-10-13,2027-10-13,-1000000.0,0.0,-18096.666667,True,-1.809667e+04,CLF,0.0356,LinAct360
4,2027-10-13,2028-04-13,2028-04-13,-1000000.0,0.0,-18096.666667,True,-1.809667e+04,CLF,0.0356,LinAct360
5,2028-04-13,2028-10-13,2028-10-13,-1000000.0,-1000000.0,-18096.666667,True,-1.018097e+06,CLF,0.0356,LinAct360

## Pata Fija en CLP (Banco paga)

In [35]:
fixed_rate_value = .07
clp_leg_other_values = {
    "rec_pay": qcf.RecPay.RECEIVE,
    "initial_notional": 39_505_990_000.0,
    "notional_currency": qcf.QCCLP(),
    "interest_rate": qcf.QCInterestRate(fixed_rate_value, qcf.QCAct360(), qcf.QCLinearWf()),
}

In [36]:
pata_clp = qcf.LegFactory.build_bullet_fixed_rate_leg(
     **(common_parameters | clp_leg_other_values)
)

In [37]:
aux.leg_as_dataframe(pata_clp)

,fecha_inicial,fecha_final,fecha_pago,nocional,amortizacion,interes,amort_es_flujo,flujo,moneda_nocional,valor_tasa,tipo_tasa
0,2025-10-13,2026-04-13,2026-04-13,3.950599e+10,0.000000e+00,1.398073e+09,True,1.398073e+09,CLP,0.07,LinAct360
1,2026-04-13,2026-10-13,2026-10-13,3.950599e+10,0.000000e+00,1.405755e+09,True,1.405755e+09,CLP,0.07,LinAct360
2,2026-10-13,2027-04-13,2027-04-13,3.950599e+10,0.000000e+00,1.398073e+09,True,1.398073e+09,CLP,0.07,LinAct360
3,2027-04-13,2027-10-13,2027-10-13,3.950599e+10,0.000000e+00,1.405755e+09,True,1.405755e+09,CLP,0.07,LinAct360
4,2027-10-13,2028-04-13,2028-04-13,3.950599e+10,0.000000e+00,1.405755e+09,True,1.405755e+09,CLP,0.07,LinAct360
5,2028-04-13,2028-10-13,2028-10-13,3.950599e+10,3.950599e+10,1.405755e+09,True,4.091174e+10,CLP,0.07,LinAct360

In [40]:
rec = clf_leg_other_values["initial_notional"] * .05 * 39_505.99
print(f"REC: {rec:,.0f} CLP")

REC: 1,975,299,500 CLP